Repository dsc-umass/project-matching, pull requests merged in 2020-06, with the labels that each got.

#31 fixing devise setup
  app/controllers/application_controller.rb
Labels: Development, bug, ruby

#53 Adding Docker-Compose
  README.md
  config/database.yml
  db_shell.sh
  docker-compose.yml
  docker/Dockerfile
  docker/db_setup.sh
  docker/docker_set_up.sh
  docker_shell.sh
Labels: Development, backend, dependencies, deployment, documentation

#51 Organization Tags
  app/controllers/organizations_controller.rb
  app/controllers/types_controller.rb
  app/models/organization.rb
  app/models/position.rb
  app/models/project.rb
  app/models/user.rb
  app/views/acts_as_taggable_on/tags/_tag.html.erb
  app/views/organizations/_form.html.erb
  app/views/organizations/_organization.html.erb
  app/views/organizations/index.html.erb
  app/views/organizations/show.html.erb
  app/views/tags/index.html.erb
  app/views/tags/show.html.erb
  app/views/types/index.html.erb
  app/views/types/show.html.erb
  config/routes.rb
Labels: Development, backend, enhancement, frontend, ruby
